config/routes.rb
Rails.application.routes.draw do
  resources :live_streams
  # resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :products, only: [], param: :index do
    member do
      delete '(:id)' => "products#destroy", as: ""
      post '/' => "products#create"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/live_stream.rb
class LiveStream < ApplicationRecord
	has_one_attached :image
	has_many :products
  	accepts_nested_attributes_for :products, reject_if: :all_blank, allow_destroy: true
end

app/models/product.rb
class Product < ApplicationRecord
	has_one_attached :image
	belongs_to :live_stream
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/live_streams_controller.rb
class LiveStreamsController < ApplicationController
  before_action :set_live_stream, only: %i[ show edit update destroy ]

  # GET /live_streams or /live_streams.json
  def index
    @live_streams = LiveStream.all
  end

  # GET /live_streams/1 or /live_streams/1.json
  def show
  end

  # GET /live_streams/new
  def new
    @live_stream = LiveStream.new(products: [Product.new])
  end

  # GET /live_streams/1/edit
  def edit
  end

  # POST /live_streams or /live_streams.json
  def create
    # binding.pry
    @live_stream = LiveStream.new(live_stream_params)
    # binding.pry
    respond_to do |format|
      if @live_stream.save
        format.html { redirect_to live_stream_url(@live_stream), notice: "Live stream was successfully created." }
        format.json { render :show, status: :created, location: @live_stream }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @live_stream.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /live_streams/1 or /live_streams/1.json
  def update
    respond_to do |format|
      if @live_stream.update(live_stream_params)
        format.html { redirect_to live_stream_url(@live_stream), notice: "Live stream was successfully updated." }
        format.json { render :show, status: :ok, location: @live_stream }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @live_stream.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /live_streams/1 or /live_streams/1.json
  def destroy
    @live_stream.destroy

    respond_to do |format|
      format.html { redirect_to live_streams_url, notice: "Live stream was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_live_stream
      @live_stream = LiveStream.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def live_stream_params
      # binding.pry
      params.require(:live_stream).permit(:title, :start_time, :start_date, :live_stream_product, products_attributes: [:id, :title, :description, :price, :_destroy])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :setup_project

  def new
  end

  def destroy
  end

  private

  def setup_project
    @project = LiveStream.new(products: [Product.new])
  end
  # before_action :set_product, only: %i[ show edit update destroy ]

  # # GET /products or /products.json
  # def index
  #   @products = Product.all
  # end

  # # GET /products/1 or /products/1.json
  # def show
  # end

  # # GET /products/new
  # def new
  #   @product = Product.new
  # end

  # # GET /products/1/edit
  # def edit
  # end

  # # POST /products or /products.json
  # def create
  #   @product = Product.new(product_params)

  #   respond_to do |format|
  #     if @product.save
  #       format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
  #       format.json { render :show, status: :created, location: @product }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @product.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PATCH/PUT /products/1 or /products/1.json
  # def update
  #   respond_to do |format|
  #     if @product.update(product_params)
  #       format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
  #       format.json { render :show, status: :ok, location: @product }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @product.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /products/1 or /products/1.json
  # def destroy
  #   @product.destroy

  #   respond_to do |format|
  #     format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end


  # before_action :setup_project

  # def new
  # end

  # def destroy
  # end

  # private

  # def setup_project
  #   @project = LiveStream.new(products: [Product.new])
  # end

  # private
  #   # Use callbacks to share common setup or constraints between actions.
  #   def set_product
  #     @product = Product.find(params[:id])
  #   end

  #   # Only allow a list of trusted parameters through.
  #   def product_params
  #     params.require(:product).permit(:price, :title, :description)
  #   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/live_streams_helper.rb
module LiveStreamsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sampleapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/live_streams/_form.html.erb
<%= form_with(model: live_stream) do |form| %>
  <% if live_stream.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(live_stream.errors.count, "error") %> prohibited this live_stream from being saved:</h2>

      <ul>
        <% live_stream.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :start_time, style: "display: block" %>
    <%= form.date_field :start_time %>
  </div>

  <div>
    <%= form.label :start_date, style: "display: block" %>
    <%= form.datetime_field :start_date %>
  </div>

  <div>
    <%= form.label :live_stream_product, style: "display: block" %>
    <%= form.number_field :live_stream_product %>
  </div>


  <h4>Products</h4>
  <div id="products">
    <%= form.fields_for :products do |product_form| %>
      <%= render "products/products", form: product_form %>
    <% end %>
  </div>
  <%= form.submit "Add product", 
      formaction: product_path(@live_stream.products.size), 
      formmethod: :post, 
      formnovalidate: true, 
      id: "add-product" %>

  <div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/live_streams/_live_stream.html.erb
<div id="<%= dom_id live_stream %>">
  <p>
    <strong>Title:</strong>
    <%= live_stream.title %>
  </p>

  <p>
    <strong>Start time:</strong>
    <%= live_stream.start_time %>
  </p>

  <p>
    <strong>Start date:</strong>
    <%= live_stream.start_date %>
  </p>

  <p>
    <strong>Live stream product:</strong>
    <%= live_stream.live_stream_product %>
  </p>

</div>

app/views/live_streams/_nest_products.html.erb
<% binding.pry %>
<%= form.hidden_field :id %>

<div>
  <%= form.label :description, style: "display: block" %>
  <%= form.text_field :description %>
</div>

app/views/live_streams/edit.html.erb
<h1>Editing live stream</h1>

<%= render "form", live_stream: @live_stream %>

<br>

<div>
  <%= link_to "Show this live stream", @live_stream %> |
  <%= link_to "Back to live streams", live_streams_path %>
</div>

app/views/live_streams/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Live streams</h1>

<div id="live_streams">
  <% @live_streams.each do |live_stream| %>
    <%= render live_stream %>
    <p>
      <%= link_to "Show this live stream", live_stream %>
    </p>
  <% end %>
</div>

<%= link_to "New live stream", new_live_stream_path %>

app/views/live_streams/new.html.erb
<h1>New live stream</h1>

<%= render "form", live_stream: @live_stream %>

<br>

<div>
  <%= link_to "Back to live streams", live_streams_path %>
</div>

app/views/live_streams/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @live_stream %>

<div>
  <%= link_to "Edit this live stream", edit_live_stream_path(@live_stream) %> |
  <%= link_to "Back to live streams", live_streams_path %>

  <%= button_to "Destroy this live stream", @live_stream, method: :delete %>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= product.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

</div>

app/views/products/_products.html.erb
<%= turbo_frame_tag "product_#{form.index}" do %>
  <%= form.hidden_field :id %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>
  <%= form.submit "destroy product", 
        formaction: product_path(form.index, form.object.id), 
        formmethod: :delete, 
        formnovalidate: true, 
        data: { turbo_frame: "product_#{form.index}" } %>
<% end %>

app/views/products/create.turbo_stream.erb
<%# app/views/products/create.turbo_stream.erb %>
<%= fields model: @project do |form| %>
  <%= form.fields_for :products, child_index: params[:index] do |product_form| %>
    <%= turbo_stream.replace "add-product" do %>
      <%= form.submit "Add product", 
            formaction: product_path(product_form.index.to_i + 1), 
            formmethod: :post, 
            formnovalidate: true, 
            id: "add-product" %>
    <% end %>

    <%= turbo_stream.append "products" do %>
      <%= render "products", form: product_form %>
    <% end %>
  <% end %>
<% end %>

app/views/products/destroy.html.erb
<%# app/views/products/destroy.html.slim %>
<%= fields model: @project do |form| %>
  <%= form.fields_for :products, child_index: params[:index] do |product_form| %>
    <%= turbo_frame_tag "product_#{product_form.index}" do %>
      <%= product_form.hidden_field :id, value: params[:id] %>
      <%= product_form.hidden_field :_destroy, value: true %>
    <% end %>
  <% end %>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Products</h1>

<div id="products">
  <% @products.each do |product| %>
    <%= render product %>
    <p>
      <%= link_to "Show this product", product %>
    </p>
  <% end %>
</div>

<%= link_to "New product", new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>